[project]
name = "ernest"
version = "0.1.0"
description = "AI Also Rises"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "deptry>=0.21.1",
    "pyright>=1.1.389",
    "ruff>=0.8.1",
]
